import Head from 'next/head';
import MapContainer from '@/components/map.component';
import Header from '@/components/header.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Oavel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MapContainer />
      </main>
    </>
  );
}
